name: Deploy environment

on:
  push

jobs:
  prepare-deployment:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
      environment: ${{ steps.env.outputs.value }}
    steps:
      - name: Checkout environment code
        uses: actions/checkout@v5

      - id: matrix
        run: |
          echo "value="`cat applications.json` >> $GITHUB_OUTPUT

      - id: env
        run: |
          echo "value="`cat environment.json` >> $GITHUB_OUTPUT

      - run: |
          echo "Using environment configuration: ${{ steps.env.outputs.value }}"
          echo "Using application configuration: ${{ steps.matrix.outputs.value }}"
          echo "GH Output is $GITHUB_OUTPUT"

  perform-deployment:
    environment: aws
    needs: [ prepare-deployment ]
    uses: jpbarto/cicd-environ.cicd/.github/workflows/reuse-app-deploy.yaml@main
    strategy:
      max-parallel: 1
      matrix:
        value: ${{ fromJSON(needs.prepare-deployment.outputs.matrix) }}
    with:
      repository: ${{ matrix.value.repository }}
      release: ${{ matrix.value.release }}
      tf_vars: ${{ matrix.value.tf_vars }}
      helm_values: ${{ matrix.value.helm_values }}
      env_name: ${{ fromJSON(needs.prepare-deployment.outputs.environment).environment_name }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
